<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * Creates the notifications table for system alerts and reminders.
     * Auto-generated by scheduled jobs and business events.
     */
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade')->comment('Recipient user');
            $table->enum('type', [
                'expiry_alert',
                'low_stock',
                'reorder_point',
                'approval_required',
                'system'
            ])->comment('Notification type');
            $table->string('title')->comment('Notification title');
            $table->text('message')->comment('Notification message');
            $table->json('data')->nullable()->comment('Additional notification data (JSON)');
            $table->boolean('is_read')->default(false)->comment('Read status');
            $table->timestamp('read_at')->nullable()->comment('Read timestamp');
            $table->timestamps();
            
            // Indexes
            $table->index(['user_id', 'is_read', 'created_at']);
            $table->index(['type', 'created_at']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};

